# Kamelet source properties
camel.kamelet.aws-s3-source.bucketNameOrArn=citrus-camel-demo
camel.kamelet.aws-s3-source.region=us-east-1
camel.kamelet.aws-s3-source.accessKey=accesskey
camel.kamelet.aws-s3-source.secretKey=secretkey

# Kafka endpoint
kafka.bootstrap.servers=my-cluster.namespace.local
%test.kafka.bootstrap.servers=localhost:9092
