# AWS S3 endpoint
aws.s3.bucketNameOrArn=citrus-camel-demo
aws.s3.region=us-east-1
aws.s3.uriEndpointOverride=http://localhost:4566
aws.s3.accessKey=accesskey
aws.s3.secretKey=secretkey

# Kafka endpoint
kafka.bootstrap.servers=localhost:9092
