# Knative Camel component
camel.component.knative.environment-path=classpath:knative.json

# Wire the SSL-capable HTTP client options into the Knative component
camel.component.knative.producerFactory.clientOptions=#bean:knativeHttpClientOptions

# Knative CloudEvent attributes produced by this application
camel.component.knative.ceOverride[ce-type]=dev.knative.eventing.aws-s3
camel.component.knative.ceOverride[ce-source]=dev.knative.eventing.aws-s3-source
camel.component.knative.ceOverride[ce-subject]=aws-s3-source

# K_SINK usually injected by Knative SinkBinding, in test scope use localhost pointing to Citrus Knative broker (HTTPS)
%test.k.sink=https://localhost:8443
