quarkus.cxf.path=/cxf/services

# Generate model objects from WSDL
quarkus.cxf.codegen.wsdl2java.includes=wsdl/FruitService.wsdl

# External SOAP WebService URL (Citrus server in tests)
fruit.service.url=http://localhost:18080/services/fruits
